Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('Proto'), Integer(2)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(Equality(Symbol('SrcPt'), Integer(123)), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0))))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('Proto'), Integer(1)))
Implies(Equality(Symbol('SrcPt'), Integer(993)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(1))), And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('DstPt'), Integer(8)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
GreaterThan(Symbol('Proto'), Integer(0))
Implies(Equality(Symbol('DstPt'), Integer(0)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(443)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(Equality(Symbol('DstPt'), Integer(68)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(Equality(Symbol('Proto'), Integer(3)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(4)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcPt'), Integer(53))))
LessThan(Symbol('DstIpAddr'), Integer(4))
LessThan(Symbol('SrcIpAddr'), Integer(4))
LessThan(Symbol('Flags'), Integer(1))
Implies(And(Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('SrcPt'), Integer(0)), Equality(Symbol('Flags'), Integer(0)))
LessThan(Symbol('Proto'), Integer(3))
Implies(Equality(Symbol('DstPt'), Integer(53)), And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('SrcPt'), Integer(53)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(4))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('Proto'), Integer(2)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('DstPt'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(0))), And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('DstPt'), Integer(138)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(138))))
Implies(Equality(Symbol('DstPt'), Integer(123)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(And(Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
LessThan(Symbol('SrcPt'), Integer(60000))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('DstPt'), Integer(80)), And(Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('DstPt'), Integer(137)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(137))))
LessThan(Symbol('DstPt'), Integer(60000))
GreaterThan(Symbol('Flags'), Integer(0))
Implies(Equality(Symbol('DstPt'), Integer(25)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('DstPt'), Integer(8080)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
GreaterThan(Symbol('SrcPt'), Integer(0))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(11)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(67)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(1))), Equality(Symbol('SrcPt'), Integer(60000)))
GreaterThan(Symbol('SrcIpAddr'), Integer(0))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Flags'), Integer(1))), And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('SrcPt'), Integer(137)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(22)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(60000))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(53))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(123))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(53)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(993)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('DstPt'), Integer(443)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('DstPt'), Integer(3)))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(4))), Equality(Symbol('Proto'), Integer(1)))
Implies(Equality(Symbol('SrcPt'), Integer(138)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(138)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(68)), And(Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(60000)))
GreaterThan(Symbol('DstIpAddr'), Integer(0))
Implies(Equality(Symbol('SrcPt'), Integer(8080)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(Equality(Symbol('DstPt'), Integer(22)), And(Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(60000))), And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(Equality(Symbol('SrcPt'), Integer(80)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0))))
Implies(Equality(Symbol('Proto'), Integer(2)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(3)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcPt'), Integer(0))))
GreaterThan(Symbol('DstPt'), Integer(0))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), Equality(Symbol('DstPt'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Proto'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(0))), Equality(Symbol('Proto'), Integer(1)))
Implies(Equality(Symbol('SrcPt'), Integer(67)), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(3)))
