GreaterThan(Symbol('ActiveMax'), Symbol('ActiveMean'))
GreaterThan(Symbol('ActiveMax'), Symbol('ActiveMin'))
GreaterThan(Symbol('ActiveMax'), Symbol('ActiveStd'))
GreaterThan(Symbol('ActiveMean'), Symbol('ActiveMin'))
GreaterThan(Symbol('BwdIatMax'), Symbol('BwdIatMean'))
GreaterThan(Symbol('BwdIatMax'), Symbol('BwdIatMin'))
GreaterThan(Symbol('BwdIatMax'), Symbol('BwdIatStd'))
GreaterThan(Symbol('BwdIatMean'), Symbol('BwdIatMin'))
GreaterThan(Symbol('BwdPacketLengthMax'), Symbol('BwdPacketLengthMean'))
GreaterThan(Symbol('BwdPacketLengthMax'), Symbol('BwdPacketLengthMin'))
GreaterThan(Symbol('BwdPacketLengthMax'), Symbol('BwdPacketLengthStd'))
GreaterThan(Symbol('BwdPacketLengthMean'), Symbol('BwdPacketLengthMin'))
GreaterThan(Symbol('FlowIatMax'), Symbol('FlowIatMean'))
GreaterThan(Symbol('FlowIatMax'), Symbol('FlowIatMin'))
GreaterThan(Symbol('FlowIatMean'), Symbol('FlowIatMin'))
GreaterThan(Symbol('FwdIatMax'), Symbol('FwdIatMean'))
GreaterThan(Symbol('FwdIatMax'), Symbol('FwdIatMin'))
GreaterThan(Symbol('FwdIatMax'), Symbol('FwdIatStd'))
GreaterThan(Symbol('FwdIatMean'), Symbol('FwdIatMin'))
GreaterThan(Symbol('FwdPacketLengthMax'), Symbol('FwdPacketLengthMean'))
GreaterThan(Symbol('FwdPacketLengthMax'), Symbol('FwdPacketLengthMin'))
GreaterThan(Symbol('FwdPacketLengthMax'), Symbol('FwdPacketLengthStd'))
GreaterThan(Symbol('FwdPacketLengthMax'), Symbol('MinPacketLength'))
GreaterThan(Symbol('FwdPacketLengthMean'), Symbol('FwdPacketLengthMin'))
GreaterThan(Symbol('FwdPacketLengthMean'), Symbol('MinPacketLength'))
GreaterThan(Symbol('FwdPacketLengthMin'), Symbol('MinPacketLength'))
GreaterThan(Symbol('IdleMax'), Symbol('IdleMean'))
GreaterThan(Symbol('IdleMax'), Symbol('IdleMin'))
GreaterThan(Symbol('IdleMax'), Symbol('IdleStd'))
GreaterThan(Symbol('IdleMean'), Symbol('IdleMin'))
Implies(Or(And(StrictGreaterThan(Symbol('AckFlagCount'), Integer(0)), Unequality(Symbol('Protocol'), Integer(6))), And(StrictGreaterThan(Symbol('EceFlagCount'), Integer(0)), StrictGreaterThan(Symbol('PshFlagCount'), Integer(0))), And(StrictGreaterThan(Symbol('FinFlagCount'), Integer(0)), StrictGreaterThan(Symbol('FwdPshFlags'), Integer(0))), And(StrictGreaterThan(Symbol('FinFlagCount'), Integer(0)), StrictGreaterThan(Symbol('SynFlagCount'), Integer(0)))), StrictGreaterThan(Symbol('RstFlagCount'), Integer(0)))
Implies(Or(And(StrictGreaterThan(Symbol('EceFlagCount'), Integer(0)), StrictGreaterThan(Symbol('FinFlagCount'), Integer(0))), And(StrictGreaterThan(Symbol('FwdPshFlags'), Integer(0)), StrictGreaterThan(Symbol('PshFlagCount'), Integer(0)))), StrictLessThan(Symbol('CweFlagCount'), Integer(0)))
Implies(Or(And(StrictGreaterThan(Symbol('FwdPshFlags'), Integer(0)), StrictGreaterThan(Symbol('RstFlagCount'), Integer(0))), And(StrictGreaterThan(Symbol('PshFlagCount'), Integer(0)), StrictGreaterThan(Symbol('UrgFlagCount'), Integer(0))), And(StrictGreaterThan(Symbol('RstFlagCount'), Integer(0)), Unequality(Symbol('Protocol'), Integer(6)))), StrictLessThan(Symbol('BwdPshFlags'), Integer(0)))
Implies(And(StrictGreaterThan(Symbol('AckFlagCount'), Integer(0)), StrictGreaterThan(Symbol('PshFlagCount'), Integer(0))), StrictGreaterThan(Symbol('TotalLengthOfFwdPackets'), Integer(0)))
Implies(And(StrictGreaterThan(Symbol('AckFlagCount'), Integer(0)), StrictGreaterThan(Symbol('RstFlagCount'), Integer(0))), StrictGreaterThan(Symbol('BwdPshFlags'), Integer(0)))
Implies(Or(StrictGreaterThan(Symbol('AckFlagCount'), Integer(0)), StrictGreaterThan(Symbol('PshFlagCount'), Integer(0)), StrictGreaterThan(Symbol('TotalLengthOfFwdPackets'), Integer(0))), Unequality(Symbol('Protocol'), Integer(0)))
Implies(Or(StrictGreaterThan(Symbol('BwdPshFlags'), Integer(0)), And(Equality(Symbol('Protocol'), Integer(17)), StrictGreaterThan(Symbol('EceFlagCount'), Integer(0))), And(StrictGreaterThan(Symbol('FinFlagCount'), Integer(0)), StrictGreaterThan(Symbol('UrgFlagCount'), Integer(0))), And(StrictGreaterThan(Symbol('UrgFlagCount'), Integer(0)), Unequality(Symbol('Protocol'), Integer(6)))), StrictGreaterThan(Symbol('PshFlagCount'), Integer(0)))
Implies(Or(StrictGreaterThan(Symbol('BwdUrgFlags'), Integer(0)), And(Equality(Symbol('Protocol'), Integer(17)), StrictGreaterThan(Symbol('AckFlagCount'), Integer(0))), And(StrictGreaterThan(Symbol('AckFlagCount'), Integer(0)), StrictGreaterThan(Symbol('EceFlagCount'), Integer(0))), And(StrictGreaterThan(Symbol('RstFlagCount'), Integer(0)), StrictGreaterThan(Symbol('UrgFlagCount'), Integer(0)))), StrictGreaterThan(Symbol('FwdPshFlags'), Integer(0)))
Implies(Or(StrictGreaterThan(Symbol('CweFlagCount'), Integer(0)), StrictGreaterThan(Symbol('RstFlagCount'), Integer(0))), Unequality(Symbol('Protocol'), Integer(17)))
Implies(Or(And(Equality(Symbol('Protocol'), Integer(0)), StrictGreaterThan(Symbol('AckFlagCount'), Integer(0))), And(Equality(Symbol('Protocol'), Integer(0)), StrictGreaterThan(Symbol('TotalLengthOfFwdPackets'), Integer(0))), And(Equality(Symbol('Protocol'), Integer(17)), StrictGreaterThan(Symbol('PshFlagCount'), Integer(0))), And(StrictGreaterThan(Symbol('FinFlagCount'), Integer(0)), StrictGreaterThan(Symbol('RstFlagCount'), Integer(0)))), StrictGreaterThan(Symbol('UrgFlagCount'), Integer(0)))
Implies(Or(And(Equality(Symbol('Protocol'), Integer(0)), StrictGreaterThan(Symbol('EceFlagCount'), Integer(0))), And(Equality(Symbol('Protocol'), Integer(17)), StrictGreaterThan(Symbol('FwdPshFlags'), Integer(0)))), StrictLessThan(Symbol('AckFlagCount'), Integer(0)))
Implies(Or(And(Equality(Symbol('Protocol'), Integer(0)), StrictGreaterThan(Symbol('FinFlagCount'), Integer(0))), And(Equality(Symbol('Protocol'), Integer(0)), StrictGreaterThan(Symbol('UrgFlagCount'), Integer(0)))), StrictLessThan(Symbol('PshFlagCount'), Integer(0)))
Implies(Or(And(Equality(Symbol('Protocol'), Integer(0)), StrictGreaterThan(Symbol('PshFlagCount'), Integer(0))), And(StrictGreaterThan(Symbol('EceFlagCount'), Integer(0)), Unequality(Symbol('Protocol'), Integer(6)))), StrictGreaterThan(Symbol('AckFlagCount'), Integer(0)))
Implies(Or(And(Equality(Symbol('Protocol'), Integer(0)), StrictGreaterThan(Symbol('SynFlagCount'), Integer(0))), And(StrictGreaterThan(Symbol('FinFlagCount'), Integer(0)), StrictGreaterThan(Symbol('PshFlagCount'), Integer(0)))), StrictGreaterThan(Symbol('TotalLengthOfBwdPackets'), Integer(0)))
Implies(Or(And(Equality(Symbol('Protocol'), Integer(0)), StrictGreaterThan(Symbol('TotalLengthOfBwdPackets'), Integer(0))), And(StrictGreaterThan(Symbol('FinFlagCount'), Integer(0)), Unequality(Symbol('Protocol'), Integer(6)))), StrictGreaterThan(Symbol('BwdUrgFlags'), Integer(0)))
Implies(Or(And(Equality(Symbol('Protocol'), Integer(17)), StrictGreaterThan(Symbol('RstFlagCount'), Integer(0))), And(StrictGreaterThan(Symbol('PshFlagCount'), Integer(0)), Unequality(Symbol('Protocol'), Integer(6)))), StrictLessThan(Symbol('UrgFlagCount'), Integer(0)))
Implies(Or(StrictGreaterThan(Symbol('FinFlagCount'), Integer(0)), StrictGreaterThan(Symbol('SynFlagCount'), Integer(0)), StrictGreaterThan(Symbol('UrgFlagCount'), Integer(0))), Equality(Symbol('Protocol'), Integer(6)))
Implies(Or(StrictGreaterThan(Symbol('FwdPshFlags'), Integer(0)), And(Equality(Symbol('Protocol'), Integer(17)), StrictGreaterThan(Symbol('FinFlagCount'), Integer(0)))), StrictGreaterThan(Symbol('SynFlagCount'), Integer(0)))
Implies(Or(StrictGreaterThan(Symbol('FwdUrgFlags'), Integer(0)), And(StrictGreaterThan(Symbol('EceFlagCount'), Integer(0)), StrictGreaterThan(Symbol('UrgFlagCount'), Integer(0))), And(StrictGreaterThan(Symbol('FwdPshFlags'), Integer(0)), Unequality(Symbol('Protocol'), Integer(6))), And(StrictGreaterThan(Symbol('SynFlagCount'), Integer(0)), Unequality(Symbol('Protocol'), Integer(6)))), StrictGreaterThan(Symbol('FinFlagCount'), Integer(0)))
Implies(And(StrictGreaterThan(Symbol('PshFlagCount'), Integer(0)), StrictGreaterThan(Symbol('SynFlagCount'), Integer(0))), StrictGreaterThan(Symbol('CweFlagCount'), Integer(0)))
Implies(And(StrictGreaterThan(Symbol('RstFlagCount'), Integer(0)), StrictGreaterThan(Symbol('SynFlagCount'), Integer(0))), Equality(Symbol('Protocol'), Integer(17)))
Implies(StrictGreaterThan(Symbol('EceFlagCount'), Integer(0)), Or(StrictGreaterThan(Symbol('PshFlagCount'), Integer(0)), StrictGreaterThan(Symbol('SynFlagCount'), Integer(0))))
Implies(And(Equality(Symbol('Protocol'), Integer(0)), StrictGreaterThan(Symbol('FwdPshFlags'), Integer(0))), StrictLessThan(Symbol('SynFlagCount'), Integer(0)))
Implies(And(Equality(Symbol('Protocol'), Integer(0)), StrictGreaterThan(Symbol('RstFlagCount'), Integer(0))), StrictLessThan(Symbol('TotalLengthOfFwdPackets'), Integer(0)))
Implies(Equality(Symbol('Protocol'), Integer(0)), GreaterThan(Symbol('BwdIatMean'), Symbol('BwdPacketLengthMax')))
Implies(And(Equality(Symbol('Protocol'), Integer(17)), StrictGreaterThan(Symbol('SynFlagCount'), Integer(0))), StrictLessThan(Symbol('FinFlagCount'), Integer(0)))
Implies(And(Equality(Symbol('Protocol'), Integer(17)), StrictGreaterThan(Symbol('UrgFlagCount'), Integer(0))), StrictLessThan(Symbol('EceFlagCount'), Integer(0)))
Implies(Equality(Symbol('Protocol'), Integer(17)), GreaterThan(Symbol('FlowIatMax'), Symbol('BwdIatStd')))
Implies(Equality(Symbol('Protocol'), Integer(6)), GreaterThan(Symbol('IdleMax'), Symbol('ActiveMin')))
Implies(Unequality(Symbol('Protocol'), Integer(0)), GreaterThan(Symbol('FwdIatMax'), Symbol('IdleStd')))
Implies(Unequality(Symbol('Protocol'), Integer(6)), GreaterThan(Symbol('FwdIatMean'), Symbol('FwdPacketLengthStd')))
Implies(StrictGreaterThan(Symbol('TotalLengthOfBwdPackets'), Integer(0)), Or(Equality(Symbol('Protocol'), Integer(6)), StrictGreaterThan(Symbol('TotalLengthOfFwdPackets'), Integer(0))))
GreaterThan(Symbol('MaxPacketLength'), Symbol('BwdPacketLengthMax'))
GreaterThan(Symbol('MaxPacketLength'), Symbol('BwdPacketLengthMean'))
GreaterThan(Symbol('MaxPacketLength'), Symbol('BwdPacketLengthMin'))
GreaterThan(Symbol('MaxPacketLength'), Symbol('BwdPacketLengthStd'))
GreaterThan(Symbol('MaxPacketLength'), Symbol('FwdPacketLengthMax'))
GreaterThan(Symbol('MaxPacketLength'), Symbol('FwdPacketLengthMean'))
GreaterThan(Symbol('MaxPacketLength'), Symbol('FwdPacketLengthMin'))
GreaterThan(Symbol('MaxPacketLength'), Symbol('FwdPacketLengthStd'))
GreaterThan(Symbol('MaxPacketLength'), Symbol('MinPacketLength'))
