Ne(SrcIpAddr, 1)
Ne(DstIpAddr, 2)
Equivalent(Eq(Proto, 0), Eq(Flags, 1))
Eq(SrcPt, 80) >> Eq(Proto, 0)
Eq(SrcPt, 443) >> Eq(Proto, 0)
Eq(SrcPt, 8080) >> Eq(Proto, 0)
Eq(SrcPt, 53) >> Eq(DstIpAddr, 0)
Equivalent(Eq(SrcPt, 53), Eq(SrcIpAddr, 4))
Eq(DstPt, 53) >> Eq(DstIpAddr, 4)
Eq(DstIpAddr, 4) >> (Eq(DstPt, 53) | Eq(DstPt, 3))
Eq(DstIpAddr, 3) >> Ne(SrcPt, 80)
Eq(DstIpAddr, 3) >> Ne(SrcPt, 443)
Eq(DstIpAddr, 3) >> Ne(SrcPt, 8080)
42*Packets <= Bytes
65535*Packets >= Bytes
Eq(SrcIpAddr, 3) >> ~(Eq(SrcPt, 137) | Eq(SrcPt, 138))
Eq(DstIpAddr, 3) >> ~(Eq(DstPt, 137) | Eq(DstPt, 138))
Eq(SrcIpAddr, 3) >> (Eq(DstIpAddr, 0) | Eq(DstIpAddr, 1))
Eq(SrcIpAddr, 4) >> (Eq(DstIpAddr, 0) | Eq(DstIpAddr, 1))
Eq(DstIpAddr, 3) >> (Eq(SrcIpAddr, 0) | Eq(SrcIpAddr, 2))
Eq(DstIpAddr, 4) >> (Eq(SrcIpAddr, 0) | Eq(SrcIpAddr, 2))
Eq(DstPt, 137) >> (Eq(DstIpAddr, 1) & Eq(SrcIpAddr, 0))
Eq(DstPt, 138) >> (Eq(DstIpAddr, 1) & Eq(SrcIpAddr, 0))
Or(Eq(DstPt, 137), Eq(DstPt, 138)) >> Eq(DstIpAddr, 1)
Or(Eq(DstPt, 137), Eq(DstPt, 138)) >> Eq(SrcIpAddr, 0)
Eq(Proto, 2) >> (64*Packets <= Bytes)
Eq(Proto, 2) >> (65535*Packets >= Bytes)
Eq(Proto, 2) >> Eq(SrcPt, 0)